steps:
  # Krok 1: Budowa obrazu Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/leadgenerator:$COMMIT_SHA', '.']

  # Krok 2: Wypchnięcie zbudowanego obrazu do Google Container/Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/leadgenerator:$COMMIT_SHA']

  # Krok 3: Publikacja na usłudze Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'leadgenerator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/leadgenerator:$COMMIT_SHA'
      - '--region'
      - 'europe-central2' 
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Deklaracja obrazów stworzonych w trakcie buildu
images:
  - 'gcr.io/$PROJECT_ID/leadgenerator:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
